-- Catchus abandoned customer cleanup
-- Run after customer_auth.sql.
--
-- This migration is safe to re-run and stores no API credentials. Supabase
-- Cron invokes the protected PostgreSQL function directly every five minutes.
-- Keep the Supabase Auth email OTP expiry at 3600 seconds or longer so every
-- confirmation link remains valid throughout the one-hour cleanup window.

create extension if not exists pg_cron with schema pg_catalog;

create table if not exists public.auth_cleanup_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email text,
  user_created_at timestamptz not null,
  cleanup_at timestamptz not null default now(),
  status text not null,
  error_message text,
  constraint auth_cleanup_logs_status_valid check (
    status in ('processing', 'deleted', 'failed')
  )
);

comment on table public.auth_cleanup_logs is
  'Identity snapshot and outcome for each abandoned-account deletion attempt.';

-- Customer-owned tables added in future phases must reference auth.users(id)
-- with ON DELETE CASCADE. Deleting auth.users then removes the entire customer
-- aggregate while this audit table intentionally remains for operations logs.

create index if not exists idx_auth_cleanup_logs_user_id
  on public.auth_cleanup_logs (user_id);
create index if not exists idx_auth_cleanup_logs_cleanup_at
  on public.auth_cleanup_logs (cleanup_at desc);

alter table public.auth_cleanup_logs enable row level security;
revoke all on public.auth_cleanup_logs from anon, authenticated;
revoke all on sequence public.auth_cleanup_logs_id_seq from anon, authenticated;
-- Remove grants left by the previous HTTP worker migration. The scheduled
-- database function runs as its owner and does not need an API role.
revoke all on public.auth_cleanup_logs from service_role;
revoke all on sequence public.auth_cleanup_logs_id_seq from service_role;

create or replace function public.cleanup_unverified_customer_accounts()
returns table (
  scanned_count integer,
  deleted_count integer,
  failed_count integer
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  candidate record;
  cleanup_log_id bigint;
  affected_rows integer;
  cutoff_time timestamptz := pg_catalog.now() - interval '1 hour';
begin
  scanned_count := 0;
  deleted_count := 0;
  failed_count := 0;

  -- Avoid overlapping runs if one cleanup takes longer than five minutes.
  if not pg_catalog.pg_try_advisory_xact_lock(
    pg_catalog.hashtext('catchus-cleanup-unverified-users')
  ) then
    return next;
    return;
  end if;

  for candidate in
    select auth_user.id, auth_user.email, auth_user.created_at
    from auth.users as auth_user
    where auth_user.email_confirmed_at is null
      and auth_user.created_at <= cutoff_time
      and not exists (
        select 1
        from public.admin_users as admin_user
        where admin_user.id = auth_user.id
      )
    order by auth_user.created_at
    for update of auth_user skip locked
  loop
    scanned_count := scanned_count + 1;

    -- Write the identity snapshot before deletion so a deletion is never
    -- performed without a durable audit record.
    insert into public.auth_cleanup_logs (
      user_id,
      email,
      user_created_at,
      cleanup_at,
      status
    )
    values (
      candidate.id,
      candidate.email,
      candidate.created_at,
      pg_catalog.clock_timestamp(),
      'processing'
    )
    returning id into cleanup_log_id;

    begin
      -- These predicates are intentionally repeated immediately before the
      -- delete. The row lock prevents email verification from racing the
      -- cleanup, and the admin check protects the authorization allow-list.
      delete from auth.users as target_user
      where target_user.id = candidate.id
        and target_user.email_confirmed_at is null
        and target_user.created_at <= cutoff_time
        and not exists (
          select 1
          from public.admin_users as admin_user
          where admin_user.id = target_user.id
        );

      get diagnostics affected_rows = row_count;

      if affected_rows = 1 then
        update public.auth_cleanup_logs
        set status = 'deleted', error_message = null
        where id = cleanup_log_id;
        deleted_count := deleted_count + 1;
      else
        update public.auth_cleanup_logs
        set
          status = 'failed',
          error_message = 'Safety predicate no longer matched; account was not deleted.'
        where id = cleanup_log_id;
        failed_count := failed_count + 1;
      end if;
    exception
      when others then
        update public.auth_cleanup_logs
        set
          status = 'failed',
          error_message = sqlstate || ': ' || sqlerrm
        where id = cleanup_log_id;
        failed_count := failed_count + 1;
    end;
  end loop;

  return next;
end;
$function$;

comment on function public.cleanup_unverified_customer_accounts() is
  'Deletes non-admin Auth users that remain email-unverified for one hour.';

-- Only the function owner and Supabase Cron may execute the cleanup. Customer
-- and anonymous API roles cannot call this destructive operation.
revoke all on function public.cleanup_unverified_customer_accounts() from public;
revoke all on function public.cleanup_unverified_customer_accounts()
  from anon, authenticated;

-- Replace the previous HTTP job or an earlier database-native version without
-- creating duplicate schedules.
do $block$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id
  from cron.job
  where jobname = 'catchus-cleanup-unverified-users';

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;
end;
$block$;

select cron.schedule(
  'catchus-cleanup-unverified-users',
  '*/5 * * * *',
  $cron$select public.cleanup_unverified_customer_accounts();$cron$
);
